name: Run component tests and show reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  component-tests:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Install Allure command-line tool
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.15.0/allure-2.15.0.zip
          unzip allure.zip
          export PATH="$PATH:$(pwd)/allure-2.15.0/bin"
      - name: Run tests
        continue-on-error: true
        run: |
          pytest -v --alluredir=./allure-results
      - name: Show allure report
        continue-on-error: true
        run: |
          allure serve ./allure-results
