name: Run component tests and show reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  component-tests:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest --alluredir=./allure-results
      - name: Show allure report
        run: |
          allure serve ./allure-results
